version: '3.8'

services:
  fastapi_app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=mysecretpassword
      - STOCK_URL=https://www.alphavantage.co/query
      - API_KEY=

networks:
  default:
    external:
      name: my_network
